### ISSUE TITLE
Gallery

### ISSUE THREAD

**Issue by andrewchambers** [andrewchambers/janetsh#115]
Cool user prompts or functions need an official gallery for showing off.

**Comment by pauldub** [comment]
I have ported my ZSH prompt to janetsh, you can see the result here:
![Screenshot_2019-05-24_09-17-53](https://user-images.githubusercontent.com/1413158/58309547-d630c480-7e04-11e9-8ebc-117ad2f6ca93.png)

**Comment by andrewchambers** [comment]
That is awesome, I definitely want to collect screenshots and the code people can paste into their own files, perhaps as gists.

Here is my current prompt, not fancy just trying to look like bash.

https://gist.github.com/andrewchambers/9627b028b76fe376655052bbd13a1939

**Comment by pauldub** [comment]
Here are my current rc files:

https://gist.github.com/pauldub/73ee3501382ed85dc9b49a398e501da8

edit: this is a little bit old with regards to latest janetsh updates so some things are not needed anymore (like the constant string trimming...)

**Comment by andrewchambers** [comment]
> this is a little bit old with regards to latest janetsh updates so some things are not needed anymore (like the constant string trimming...)

All good - btw, don't hesitate to let me know if there are other problems. I am glad you worked out using keywords for escaping the janet symbol rules.

**Comment by bakpakin** [comment]
Really simple RC file I've been using to emulate my bash prompt, which is pretty basic.

https://gist.github.com/bakpakin/1cbb2d86e346355695778b41d300f16f

**Comment by andrewchambers** [comment]
Site is in the www directory - hosted at janet-shell.org, I will look at setting up the gallery there.

**Comment by andrewchambers** [comment]
@pauldub is it ok if I update the code for the newer janetsh before I put it on the site?

**Comment by pauldub** [comment]
@andrewchambers of course, go ahead :)

**Comment by andrewchambers** [comment]
@pauldub I fixed some bugs in the prompt code (a redirect missing a '&'), used some of the new command shorthand, and trimmed the away the extra functions people looking in the gallery might not need.

It is now in the gallery with the modified code: https://janet-shell.org/gallery.html
