### ISSUE TITLE
Don't print evaluation result when adding implicit parens

### ISSUE THREAD

**Issue by ALSchwalm** [andrewchambers/janetsh#161]
Currently when the implicit `(sh/$? ...)` wrapper is added to a chunk, we still print the result as usual. This results in a somewhat odd output like:

```
/home/adam/repos/janetsh $ ls /
bin   dev  home  lib64  mnt  proc  run   srv  tmp  var
boot  etc  lib   media  opt  root  sbin  sys  usr
0
/home/adam/repos/janetsh $ 
```

With the extra return code being printed after the output. This is a bit jarring, and I think removing it would be reasonable. Note that I don't think that /every/ call to `sh/$?` (and friends) should have this behaviour, but for the special case of implicit parens, it seems reasonable. We could also store the return code in a variable.

That said, I think actually implementing this would require we pull in most of the `repl` logic from janet, as I don't really see a good way to hook this otherwise. We can use a dynamic binding and a custom `onsignal` callback, but there is no obvious place we could set the binding that would be in effect when `repl` actually calls out to the `onsignal` handler.

Before going through that, I wanted to go ahead and open this to see if you like the idea.

**Comment by andrewchambers** [comment]
I personally like seeing the exit code to be honest, but I don't want to force it on you or other people.

> I think actually implementing this would require we pull in most of the repl logic from janet

Not sure I would want to add so much maintenance cost for a small cosmetic change, but perhaps there is a tasteful alteration of the janet repl api that can be upstreamed.

Note that it should already be possible to override the repl from an rc file, sometimes I wonder if a package manager is the right way to go and make it easy for people to share more complicated tweaks with eachother.

Overall I would love to hear what other people think, if you are reading this, do you like seeing the exit code?

**Comment by x4lldux** [comment]
Can't say anything about tastefullness of this solution, but this might work:
 - check if implicit parens are added
 - do `(setdyn :pretty-format "")`
 - run command
 - restore `:pretty-format`

**Comment by ALSchwalm** [comment]
Definitely a fair point about the maintenance overhead. I'll see if I can come up with a good patch to upstream that would make this simpler to implement.

**Comment by andrewchambers** [comment]
@ALSchwalm I have read the repl code some more in boot.janet, I it isn't as bad as I thought to have our own, we already reimplement most of what is in there.

**Comment by ALSchwalm** [comment]
Hmm, I can probably pull together a PR just to see what it ends up looking like. That said, it might be a few days

**Comment by andrewchambers** [comment]
No rush or obligation, just letting you know.
