### ISSUE TITLE
Implement builtins/functions we want to support that are missing

### ISSUE THREAD

**Issue by andrewchambers** [andrewchambers/janetsh#162]
- [x] cd
- [x] clear, mainly for convenience
- [x] (un)alias
- [ ] exit
- [ ] pushd/popd/dirs

**Comment by andrewchambers** [comment]
If the list of builtins we need to match other shells is relatively small, I might consider having them as functions and builtins implemented in terms of those functions.

**Comment by x4lldux** [comment]
I would also propose:
 - pushd, popd, dirs
 - export (once #158 is supported)

**Comment by andrewchambers** [comment]
I am not sure how export would work. the purpose of export is because in sh a variable is the same syntax as an os env var, this seems to be to disambiguate. In janetsh you must use the var keyword for a variable, so export does not seem to have any useful meaning. I suppose it would just be alternative syntax to (os/setenv)

I do admit it helps with muscle memory and that I have typed this before by accident when first switching to janet shell.

**Comment by x4lldux** [comment]
It depends on how #158 will be implemented, but in bash, env-var placed before a command is set only for that new process (spawned for that command ). `export` could be a way to make an env-var global. But if #158 will allow for both `($ ASD=1 command)` & `($ ASD=1)` than export is not needed.

**Comment by andrewchambers** [comment]
I created new issues for the remaining.
