### ISSUE TITLE
Color terminal prompt results in misaligned cursor

### ISSUE THREAD

**Issue by bakpakin** [andrewchambers/janetsh#28]
I have a custom prompt in `~/janetsh.rc` that uses ANSI escape codes to set color. While the color looks fine in the terminal, the cursor position is off. Linenoise seems to be counting the escape characters as part of the string.

**Comment by bakpakin** [comment]
Something like `(set *get-prompt* (fn [parser] "\e[31m$ \e[0m"))` should do it

**Comment by andrewchambers** [comment]
Definitely something I would like to fix, I am considering swapping to libedit, or readline or something else entirely.

**Comment by andrewchambers** [comment]
Fixed by @bakpakin
